# Generated by Django 4.1.6 on 2023-02-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
