# Generated by Django 4.1.6 on 2023-02-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patienthistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
